language: csharp

matrix:
  fast_finish: true
  allow_failures:
  - os: osx

  include:
    - os: linux
      dotnet: 5.0
      mono: none
    - os: osx
      dotnet: 5.0.101
      mono: none

branches:
  only:
  - master

script:
  - ./coverage.sh net5.0 Release
