version: 2.1

orbs:

  shellcheck: circleci/shellcheck@2

  build:
    jobs:

      run-build:
        parameters:
          image-tag:
            description: The .NET Core SDK image tag to use.
            type: string
          build-config:
            description: The build configuration, either Debug or Release.
            type: string
          framework:
            description: The .NET Core App framework target.
            type: string
        executor:
          name: dotnet-build-executor
          tag: << parameters.image-tag >>
        steps:
          - checkout
          - run:
              name: Test Coverage
              command: ./coverage.sh << parameters.framework >> << parameters.build-config >>
          - store_artifacts:
              path: ./test/TestResults/output/
              destination: /
          - store_test_results:
              path: ./test/TestResults/output/

    executors:

      dotnet-build-executor:
        parameters:
          tag:
            description: The .NET Core SDK image tag to use.
            type: string
        docker:
          - image: mcr.microsoft.com/dotnet/sdk:<<parameters.tag>>

workflows:

  "Build All Frameworks":
    jobs:
      - shellcheck/check:
          name: shellcheck
      - build/run-build:
          name: .NET 6.0 Debug
          image-tag: "6.0"
          build-config: Debug
          framework: net6.0
      - build/run-build:
          name: Alpine .NET 6.0 Debug
          image-tag: "6.0-alpine"
          build-config: Debug
          framework: net6.0
      - build/run-build:
          name: .NET 6.0 Release
          image-tag: "6.0"
          build-config: Release
          framework: net6.0
      - build/run-build:
          name: Alpine .NET 6.0 Release
          image-tag: "6.0-alpine"
          build-config: Release
          framework: net6.0
