version: 2.1

orbs:

  build:
    jobs:

      run-build:
        parameters:
          image-tag:
            description: The .NET Core SDK image tag to use.
            type: string
        executor:
          name: dotnet-build-executor
          tag: << parameters.image-tag >>
        steps:
          - checkout
          - run:
              name: Restore
              command: dotnet restore
          - run:
              name: Build
              command: dotnet build --no-restore -f netcoreapp2.0 -c Debug ./test/Castle.Core.AsyncInterceptor.Tests/Castle.Core.AsyncInterceptor.Tests.csproj
          - run:
              name: Test
              command: dotnet test --no-restore --no-build -c Debug -f netcoreapp2.0 ./test/Castle.Core.AsyncInterceptor.Tests/Castle.Core.AsyncInterceptor.Tests.csproj

      # The --no-restore parameter was added in .NET Core 2, so add a dedicated job for building .NET Core 1.1
      run-build-1-1:
        executor:
          name: dotnet-build-executor
          tag: "1.1"
        steps:
          - checkout
          - run:
              name: Restore
              command: dotnet restore
          - run:
              name: Build
              command: dotnet build -f netcoreapp1.1 -c Debug ./test/Castle.Core.AsyncInterceptor.Tests/Castle.Core.AsyncInterceptor.Tests.csproj
          - run:
              name: Test
              command: dotnet test --no-build -c Debug -f netcoreapp1.1 ./test/Castle.Core.AsyncInterceptor.Tests/Castle.Core.AsyncInterceptor.Tests.csproj

    executors:

      dotnet-build-executor:
        parameters:
          tag:
            description: The .NET Core SDK image tag to use.
            type: string
        docker:
          - image: mcr.microsoft.com/dotnet/core/sdk:<<parameters.tag>>

workflows:

  "Build All Frameworks":
    jobs:
      - build/run-build-1-1:
          name: "1.1 Build"
      - build/run-build:
          name: "2.1 Build"
          image-tag: "2.1"
      - build/run-build:
          name: "2.2 Build"
          image-tag: "2.2"
