name: CI

on:
  push:
    branches:
    - master

  pull_request:
    branches:
    - master

jobs:

  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        config:
          - Debug
          - Release
        framework:
          - net6.0
    name: Test ${{ matrix.os }} ${{ matrix.framework }} ${{ matrix.config }}

    steps:

      - uses: actions/checkout@v3

      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v3
        if: matrix.framework == 'net6.0'
        with:
          dotnet-version: 6.0.x

      - name: Test Coverage
        run: ./coverage.sh ${{ matrix.framework }} ${{ matrix.config }}

  code-coverage:
    runs-on: ubuntu-latest
    name: Code coverage
    env:
      framework: net6.0

    steps:

      - uses: actions/checkout@v3

      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Test Coverage
        run: ./coverage.sh ${{ env.framework }} Release

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./test/TestResults/output/coverage.${{ env.framework }}.cobertura.xml
          fail_ci_if_error: true

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./test/TestResults/output/coverage.${{ env.framework }}.info

      - name: Shellcheck
        run: >-
          find . -type f -name '*.sh' |
          wc -l && find . -type f -name '*.sh' |
          xargs shellcheck --external-sources --color=always
