name: Housekeeping

on:
  schedule:
    - cron: '0 5 28 * *' # "At 05:00 on day-of-month 28." https://crontab.guru/#0_5_28_*_*

  workflow_dispatch:

jobs:

  housekeeping:
    runs-on: ubuntu-latest

    steps:

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 180
          keep_minimum_runs: 50
